all:
	$(MAKE) -C CPU\ Operations all
	$(MAKE) -C Network\ Operations all
	$(MAKE) -C File\ System\ Operations all
clean:
	$(MAKE) -C CPU\ Operations clean
	$(MAKE) -C Network\ Operations clean
	$(MAKE) -C File\ System\ Operations all
